// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// parsePrimerBlast
void parsePrimerBlast(const std::string& primer_blast_tsv, const std::string& output_tsv, const long maximum_mismatches, const long minimum_length, const long maximum_length, const int num_threads);
RcppExport SEXP _rCRUXMini_parsePrimerBlast(SEXP primer_blast_tsvSEXP, SEXP output_tsvSEXP, SEXP maximum_mismatchesSEXP, SEXP minimum_lengthSEXP, SEXP maximum_lengthSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type primer_blast_tsv(primer_blast_tsvSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type output_tsv(output_tsvSEXP);
    Rcpp::traits::input_parameter< const long >::type maximum_mismatches(maximum_mismatchesSEXP);
    Rcpp::traits::input_parameter< const long >::type minimum_length(minimum_lengthSEXP);
    Rcpp::traits::input_parameter< const long >::type maximum_length(maximum_lengthSEXP);
    Rcpp::traits::input_parameter< const int >::type num_threads(num_threadsSEXP);
    parsePrimerBlast(primer_blast_tsv, output_tsv, maximum_mismatches, minimum_length, maximum_length, num_threads);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rCRUXMini_parsePrimerBlast", (DL_FUNC) &_rCRUXMini_parsePrimerBlast, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_rCRUXMini(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
