# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_primer_blast <- function(primer_blast_tsv, output_tsv, maximum_mismatches, minimum_length, maximum_length, num_threads) {
    invisible(.Call(`_rCRUXMini_parsePrimerBlast`, primer_blast_tsv, output_tsv, maximum_mismatches, minimum_length, maximum_length, num_threads))
}

